SQLab/113-spring-software-testing

- lab0/lab0.js
> [LAB0] 313560001

- lab0/lab0.js
Complete `lab0.js` to print "Hello world!"
---
> [LAB0] 313551077

- lab0/lab0.js
> [LAB0] 313554006

- lab0/lab0.js
> [LAB0] 313552023

- lab0/lab0.js
> [LAB0] 110263029

- lab0/lab0.js
> [LAB0] 110550028

- lab0/lab0.js
Complete lab0.js to print"Hello world"
---
> [LAB0] 110550158

- lab0/lab0.js
Complete lab0: Print Hello world!
---
> [LAB0] 111550083

- lab0/lab0.js
complete lab0.js to print "hello world".
---
> [LAB0] 312553027

- lab0/lab0.js
> [LAB0] 312555024

- lab0/lab0.js
Complete lab0.js to print "Hello World!"
---
> [LAB0] 313505006

- lab0/lab0.js
> [LAB0] 313551022

- lab0/lab0.js
> [LAB0] 313551054

- lab0/lab0.js
> [LAB0] 313551091

- lab0/lab0.js
> [LAB0] 313551109

- lab0/lab0.js
> [LAB0] 313551149

- lab0/lab0.js
Complete lab0.js to print "Hello world!".
---
> [LAB0] 313552009

- lab0/lab0.js
> [LAB0] 313552017

- lab0/lab0.js
Complete printing "Hello world!" in lab0.js
---
> [LAB0] 313552024

- lab0/lab0.js
Print "Hello world!" as required for the Lab 0.
---
> [LAB0] 313552031

- lab0/lab0.js
> [LAB0] 313553801

- lab0/lab0.js
> [LAB0] 313554033

- lab0/lab0.js
> [LAB0] 313581017

- lab0/lab0.js
> [LAB0] 313581030

- lab0/lab0.js
> [LAB0] 313553053

- lab0/lab0.js
> [LAB0] 313581042

- lab0/lab0.js
> [LAB0] 313551169

- lab0/lab0.js
> [LAB0] a131035

- lab0/lab0.js
> [LAB0] 313561001

- lab0/lab0.js
> [LAB0] b132016

- lab0/lab0.js
> [LAB0] 313551177

- lab0/lab0.js
added a Hello World! print to the file
---
> [LAB0] 313551801

- lab0/lab0.js
> [LAB0] 312552019

- lab1/main_test.js
An unit tests for main.js, ensuring 100% code coverage. It tests the functionality of 'MyClass' and 'Student' classes using node:test and assert.
---
> [LAB1] 110550158

- lab0/lab0.js
- lab1/main_test.js
> [LAB1] 111550083

- lab1/main_test.js
> [LAB1] 312555024

- lab1/main_test.js
> [LAB1] 313505006

- lab1/main_test.js
> [LAB1] 313551054

- lab1/main_test.js
Complete `lab1/main_test.js` to test `lab1/main.js`
---
> [LAB1] 313551077

- lab1/main_test.js
Complete lab1/main_test.js to pass the test and CI
---
> [LAB1] 313551091

- lab0/lab0.js
- lab1/main_test.js
> [LAB1] 313551109

- lab1/main_test.js
[LAB1] 313552009 with Unit testing
---
> [LAB1] 313552009

- lab1/main_test.js
> [LAB1] 313552023

- lab1/main_test.js
LAB1 test with 100% coverage
---
> [LAB1] 313553005

- lab1/main_test.js
**Changes Made:**
1. **MyClass Tests**:
- Implemented tests for `addStudent` method to validate the addition of valid and invalid student objects.
- Implemented tests for `getStudentById` method to ensure it accurately retrieves student objects and handles out-of-bounds queries properly.
2. **Student Tests**:
- Implemented tests for the `setName` method to check the handling of both valid and invalid inputs.
- Implemented tests for the `getName` method to confirm it returns the correct name or an empty string if not set.
---
> [LAB1] 313553801

- lab1/main_test.js
> [LAB1] 313560001

- lab1/main_test.js
Complete Lab1 with 100% code coverage.
---
> [LAB1] 313560007

- lab1/main_test.js
Complete Lab 1 by writing unit tests for functions in main.js
---
> [LAB1] 313560008

- lab1/main_test.js
Complete lab1/main_test.js to test lab1/main.js for 100% converage
---
> [LAB1] 313581017

- lab1/main_test.js
Complete main_test.js to add unit tests for MyClass and Student
---
> [LAB1] 313581030

- lab1/main_test.js
<>
Added 100% test coverage to lab1 > main_tests.js
---
> [LAB1] 313704803

- lab1/main_test.js
An unit tests for main.js, ensuring 100% code coverage. It tests the functionality of "MyClass" and "Student" classes using node:test and assert
---
> [LAB1] 313553053

- lab1/main_test.js
Complete main_test.js to reach 100% coverage
---
> [LAB1] 313551169

- lab1/main_test.js
> [LAB1] a131035

- lab1/main_test.js
Added test for the class myClass and Student
---
> [LAB1] 313561001

- lab1/main_test.js
> [LAB1] b132016

- lab1/main_test.js
Added test cases to verify the functionality of MyClass and Student classes, ensuring that methods such as addStudent, getStudentById, setName, and getName work as expected.
---
> [LAB1] 111550064

- lab1/main_test.js
> [LAB1] 110263029

- lab2/main_test.js
finish main_test.js with coverage 100% for testing main.js
---
> [LAB2] 110550078

- lab2/main_test.js
lab2 testing coverage 100%
---
> [LAB2] 110550158

- lab2/main_test.js
> [LAB2] 312553027

- lab2/main_test.js
> [LAB2] 312555024

- lab2/main_test.js
> [LAB2] 313505006

- lab2/main_test.js
Complete the main_test.js in Lab 2 by writing testing w/ mock, stub, and spy.
---
> [LAB2] 313551022

- lab2/main_test.js
> [LAB2] 313551054

- lab2/main_test.js
> [LAB2] 313551077

- lab2/main_test.js
> [LAB2] 313551091

- lab1/main_test.js
- lab2/main_test.js
> [LAB2] 313551109

- lab2/main_test.js
> [LAB2] 313551136

- lab2/main_test.js
> [LAB2] 313552009

- lab2/main_test.js
> [LAB2] b132016

- lab2/main_test.js
Did a mock test for Application class and MailSystem class
---
> [LAB2] 313561001

- lab2/main_test.js
> [LAB2] 313551177

- lab2/main_test.js
Use mock to complete main_test.js to cover 100% coverage.
---
> [LAB2] 313551169

- lab2/main_test.js
<>
added 100% test coverage to lab2 - main_test.js
---
> [LAB2] 313704803

- lab2/main_test.js
Complete lab2/main_test.js to test lab2/main.js for 100% converage
---
> [LAB2] 313581017

- lab2/main_test.js
> [LAB2] 313560001

- lab2/main_test.js
> [LAB2] 313552023

- lab2/main_test.js
> [LAB2] 313551149

- lab2/main_test.js
This code defines unit tests for the Application and MailSystem classes, checking functionality like name selection, duplicate prevention, and email sending. It uses stubs and mocks to simulate file reading and email sending behavior.
---
> [LAB2] 111550064

- lab1/main_test.js
- lab2/main_test.js
COMPLETE LAB2 with TEST DOUBLES
---
> [LAB2] 111550083

- lab2/main_test.js
Add tests for MailSystem and Application methods
---
> [LAB2] 313581030

- lab1/main_test.js
- lab2/main_test.js
> [LAB2] 313554006

- lab2/main_test.js
> [LAB2] 110263029

- lab2/main_test.js
Complete Lab2 to apply testing on `MailSystem` and `Application`.
---
> [LAB2] 110550028

- lab2/main_test.js
Complete Test & some comments for LAB2
---
> [LAB2] 313552024

- lab2/main_test.js
Added tests for Mailsystem.write and send (success/failure cases).
Tested Application methods: constructor, getNames, getRandomPerson, selectNextPerson, and notifySelected.
Used mocks and spies for isolated testing.
---
> [LAB2] 313553801

- lab2/main_test.js
Finish Lab 2 by creating unit tests with test doubles for the functions in main.js.
---
> [LAB2] 313560008

- lab1/main_test.js
- lab2/main_test.js
get main_test.js with coverage 100% for testing main.js using unit test double
---
> [LAB2] 313552017

- lab5/antiasan.c
> [LAB5] 110263029

- lab5/antiasan.c
finish the antiasan function to pass the check of asan and perform global buffer overflow
---
> [LAB5] 110550078

- lab5/antiasan.c
> [LAB5] 110550158

- lab5/antiasan.c
> [LAB5] 312553027

- lab5/antiasan.c
> [LAB5] 312555024

- .vscode/settings.json
- lab5/antiasan.c
1. (100%) write a function antoasan to bypass detection of ASan in `antiasan.c`.
You can run `validate.sh` in your local to test if you satisfy the requirements.
---
> [LAB5] 313551010

- lab5/antiasan.c
Implemented antiasan to bypass address sanitizer.
---
> [LAB5] 313551022

- lab5/antiasan.c
> [LAB5] 313551135

- lab5/antiasan.c
> [LAB5] 313551109

- lab5/antiasan.c
> [LAB5] 313551136

- lab5/antiasan.c
> [LAB5] 313551149

- lab5/antiasan.c
Used `__asan_unpoison_memory_region()` to unpoison the memory region covering `gS` and the overflowed area
---
> [LAB5] 313552017

- lab5/antiasan.c
> [LAB5] 313552038

- lab5/antiasan.c
> [LAB5] 313553005

- lab5/antiasan.c
> [LAB5] 313554006

- lab5/antiasan.c
> [LAB5] 313560001

- lab5/antiasan.c
- lab5/antiasan.c.bak
> [LAB5] 313560003

- lab5/antiasan.c
> [LAB5] 313560007

- lab5/antiasan.c
> [LAB5] 313581017

- lab5/antiasan.c
> [LAB5] 313581030

- lab5/antiasan.c
> [LAB5] 313553053

- lab5/antiasan.c
Updating antiasan.c to bypass the detection of ASan
---
> [LAB5] 313551169

- lab5/antiasan.c
Complete antisacan to bypass ASan.
---
> [LAB5] a131035

- lab5/antiasan.c
> [LAB5] 313551177

- lab5/antiasan.c
> [LAB5] b132016

- lab2/main_test.js
- lab4/main_test.js
> [LAB4] 313581042

- lab3/main_test.js
> [LAB3] 313553034

- lab3/main_test.js
- lab5/antiasan.c
> [LAB5] 313552023

- lab3/main_test.js
> [LAB3] 110263029

- lab3/main_test.js
Learn to parameterize test cases in lab3.
---
> [LAB3] 110550028

- lab3/main_test.js
- lab3/validate.sh
Finish main_test.js for testing main.js by using parameterized testcases.
---
> [LAB3] 110550078

- lab3/main_test.js
> [LAB3] 110550158

- lab3/main_test.js
Implemented parameterized unit tests for Calculator's exp() and log() functions in main_test.js.
---
> [LAB3] 111550064

- lab2/main_test.js
- lab3/main_test.js
> [LAB3] 111550083

- lab3/main_test.js
> [LAB3] 312555024

- lab3/main_test.js
> [LAB3] 313505006

- lab3/main_test.js
> [LAB3] 313551054

- lab3/main_test.js
> [LAB3] 313551091

- lab3/main_test.js
> [LAB3] 313551109

- lab3/main_test.js
> [LAB3] 313551136

- lab5/antiasan.c
> [LAB5] 313551077

- lab5/antiasan.c
use __asan_unpoison_memory_region read global redzone，to deal with ASan test
---
> [LAB5] 313554033

- lab5/antiasan.c
bypass detection of ASan in `antiasan.c`
---
> [LAB5] 313560008

- lab6/llvm-pass.so.cc
> [LAB6] 110263029

- lab6/llvm-pass.so.cc
use llvm-pass to call debug function with argument 48763, set argc of main function as 48763, and set argv[1] to be the specific string.
---
> [LAB6] 110550078

- lab6/llvm-pass.so.cc
> [LAB6] 110550158

- lab6/llvm-pass.so.cc
Complete Lab6!!!!!!!!!!!!!!!! 48763
---
> [LAB6] 111550083

- lab6/llvm-pass.so.cc
> [LAB6] 312553027

- lab6/llvm-pass.so.cc
Write a llvm pass to instrument some codes to `target.c` in `llvm-pass.so.cc` and satisfy following requirements.
---
> [LAB6] 313551010

- lab6/llvm-pass.so.cc
Implemented LLVM pass for Lab6.
---
> [LAB6] 313551022

- lab6/llvm-pass.so.cc
lab6: update llvm-pass.so.cc
---
> [LAB6] 313551054

- lab6/llvm-pass.so.cc
> [LAB6] 313551077

- lab6/llvm-pass.so.cc
> [LAB6] 313551109

- lab6/llvm-pass.so.cc
> [LAB6] 313551136

- lab6/llvm-pass.so.cc
> [LAB6] 313551149

- lab6/llvm-pass.so.cc
> [LAB6] 313552009

- lab3/main_test.js
> [LAB3] 313552023

- lab6/llvm-pass.so.cc
> [LAB6] 313552024

- lab6/llvm-pass.so.cc
> [LAB6] 313553005

- lab6/llvm-pass.so.cc
> [LAB6] 313553034

- lab6/llvm-pass.so.cc
This pull request adds an LLVM pass that instruments the main function in target.c to invoke the debug function with the constant 48763, override argc to 48763, and set argv[1] to the string "hayaku... motohayaku!". These changes are injected at the IR level without modifying the original source code. The pass is implemented in llvm-pass.so.cc and passes validation using the provided script.
---
> [LAB6] 313553801

- lab6/llvm-pass.so.cc
> [LAB6] 313560001

- lab6/llvm-pass.so.cc
…d argument modifications
add LLVM pass to instrument target.c with custom debug an…
---
> [LAB6] 313560008

- lab6/llvm-pass.so.cc
Add LLVM pass to modify main function arguments
---
> [LAB6] 313581030

- lab6/llvm-pass.so.cc
testing third try of solution - modification of llvm-pass.so.cc. 100% of tasks complete
---
> [LAB6] 313704803

- lab6/llvm-pass.so.cc
> [LAB6] 313553053

- lab6/llvm-pass.so.cc
> [LAB6] 313581042

- lab6/llvm-pass.so.cc
Updating llvm-pass.so.cc to complete the requirement without modifying target.c.
---
> [LAB6] 313551169

- lab6/llvm-pass.so.cc
> [LAB6] a131035

- lab8/solve.py
using angr in solve.py to perform symbolic execution for finding the correct input of chal.c
---
> [LAB8] 110550078

- lab8/solve.py
> [LAB8] 110550158

- lab8/solve.py
> [LAB8] 111550083

- lab8/solve.py
> [LAB8] 312553027

- lab8/solve.py
> [LAB8] 313505006

- lab8/solve.py
(100%) Write a angr script and satisfy following requirements.
1. Explore flag is in stdout or not by angr to solve secret key.
2. Write secret key to stdout, and `validate.sh` pass it to `./chal` to check secret key.
You can run `validate.sh` in your local to test if you satisfy the requirements.
---
> [LAB8] 313551010

- lab8/solve.py
Implemented binary analysis with angr for lab8
---
> [LAB8] 313551022

- lab6/llvm-pass.so.cc
- lab8/solve.py
> [LAB8] 312555024

- lab8/solve.py
> [LAB8] 313551109

- lab8/solve.py
> [LAB8] 313551135

- lab8/solve.py
> [LAB8] 313551136

- lab8/solve.py
> [LAB8] 313551149

- lab8/solve.py
This PR adds `solve.py`, which uses symbolic execution (via angr) to automatically discover the correct 8-byte input that satisfies all the constraints in `gate()` from `chal.c`.
---
> [LAB8] 313552017

- lab8/solve.py
> [LAB8] 313552023

- lab8/solve.py
> [LAB8] 313552038

- lab8/solve.py
> [LAB8] 313553801

- lab8/solve.py
> [LAB8] 313560001

- lab8/solve.py
> [LAB8] 313560007

- lab8/solve.py
…onstraints
feat(lab8): add symbolic execution script using angr to solve input c…
---
> [LAB8] 313560008

- lab8/solve.py
modify solve.py to pass lab8
---
> [LAB8] 313581017

- lab8/solve.py
> [LAB8] 313581042

- lab8/solve.py
> [LAB8] a131035

- lab8/solve.py
> [LAB8] 313551177
